# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Chromatic Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_chromatic.yml'
      - '.storybook/**'
      - 'packages/ui/src/**'
      - '**/*.stories.tsx'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Chromatic
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - run: echo NOOP
