# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Microsite Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - run: echo NOOP
